version: '2.4'
services:

  dev-avahi:
    extends:
      service: dev
    build:
      args:
        - USE_AVAHI=1
    image: mindspy/squid-deb-proxy:${GIT_BRANCH}-avahi

  dev:
    platform: ${platform}
    build:
      context: ./
      args:
        - http_proxy
        - platform
        - USE_AVAHI=0
    image: mindspy/squid-deb-proxy:${GIT_BRANCH}

  latest:
    extends:
      service: dev
    image: mindspy/squid-deb-proxy:latest

  latest-date:
    extends:
      service: dev
    image: mindspy/squid-deb-proxy:latest-${BUILD_DATE}
