version: '2.4'
services:

  pkg-proxy:
    image: mindspy/squid-deb-proxy:latest
    container_name: pkg-proxy
    # platform: ${platform}
    volumes:
      - data-vol:/data
    networks:
      - proxy-net
    expose:
      - 8000
    environment:
      - USE_ACL=0
      - USE_AVAHI=0
      - http_proxy
    restart: unless-stopped

volumes:
  data-vol:
    name: squid-deb-proxy-data

networks:
  proxy-net:
    name: squid-deb-proxy-net
