version: '2.4'
services:

  dev:
    platform: ${platform}
    build:
      context: ./
      args:
        - http_proxy
        - platform
        - PKG_PROXY
        - USE_AVAHI=0
    image: mindspy/squid-deb-proxy:rev-${GIT_BRANCH}

  dev-avahi:
    extends:
      service: dev
    build:
      args:
        - USE_AVAHI=1
    image: mindspy/squid-deb-proxy:rev-${GIT_BRANCH}-avahi
  latest:
    extends:
      service: dev
    image: mindspy/squid-deb-proxy:latest

  latest-date:
    extends:
      service: dev
    image: mindspy/squid-deb-proxy:${BUILD_DATE}
